### ISSUE TITLE
Change ruby version for homestead

### ISSUE THREAD

**Issue by davidsoderberg** [golincode/guides#5]
Hi could you please change ruby version for homestead because I get:
"WARNING: ruby-2.1.2 is nearing its end of life."

**Comment by gbish** [comment]
Hi @davidsoderberg, currently the scripts install version 2.2.2.

It isn't designed to keep your version up to date sadly, as there's normally a bit of lag between new versions and rbenv, but that being said, a new version being present isn't a guarantee of it being 'rock solid'.

If you just need to upgrade (I assume you used this originally before the version was changed), you can just run: 

```
rbenv install 2.2.2
rbenv global 2.2.2
```

If you want the latest and greatest, 2.3.0 should also be good now.
